FROM php:7.2-apache
COPY src/ /var/www/html/
EXPOSE 80

# to build and run

# docker build -t static-site --file ./DockerFile .


# from script

docker run -it --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:7.4-cli php index.php

